export enum SignalKind {
  WebDriver = "web_driver",
  EvalLength = "eval_length",
  UserAgentData = "user_agent_data",
  UserAgent = "user_agent",
  BrowserKind = "browser_kind",
  PluginsLength = "plugins_length",
  Languages = "languages",
  WebGL = "webgl",
  Permissions = "permissions",
  ErrorTrace = "error_trace",
  ElectronProcessProps = "electron_process_props",
  AppVersion = "app_version",
  RTT = "rtt",
  WindowProps = "window_props",
  Process = "process",
  DocumentProps = "document_props",
  DocumentAttributes = "document_attributes",
  PluginsArray = "plugins_array",
  FunctionBind = "function_bind",
  WindowSize = "window_size",
  WindowExternal = "window_external",
}
