export enum SignalKind {
  WebDriver = 'web_driver',
  WindowProps = 'window_props',
  SeleniumDocumentProps = 'selenium_props',
  EvalLength = 'eval_length',
  HasUserAgentData = 'has_user_agent_data',
  UserAgent = 'user_agent',
  BrowserKind = 'browser_kind',
  PluginsLength = 'plugins_length',
  Languages = 'languages',
  WebGL = 'webgl',
  Permissions = 'permissions',
  ErrorTrace = 'error_trace',
  ElectronProcessProps = 'electron_process_props',
  AppVersion = 'app_version',
  RTT = 'rtt',
}
